/**:
  ros__parameters:
    #INTRASINC PARAMETERS
    mass: 3.3981
    max_thrust: 195.198 #195.198

    #PID GEOMETRIC
    geom_pid_trans_p: "15.0, 15.0, 10.0"
    geom_pid_trans_i: "2.0, 2.0, 2.0"
    geom_pid_trans_d: "15.0, 15.0, 15.0"
    geom_pid_rot_p: "10.0, 10.0, 10.0"
    geom_pid_rot_i: "1.0, 1.0, 0.5"
    geom_pid_rot_d: "4.0, 4.0, 4.0"

    #PID VELOCITY
    vel_pid_trans_p: "4.0, 4.0, 4.0"
    vel_pid_trans_i: "1.0, 1.0, 2.0"
    vel_pid_rot_p: "2.0, 2.0, 2.0"
    vel_pid_rot_i: "0.5, 0.5, 0.5"

    #CONTROLLER SELECT
    select_controller: 2

    #INIT POSITION
    d_position: "0.0, 0.0, 1.0"
    d_rot_euler: "0.0, 0.0, 0.0"

    #ANTI WINDUP
    anti_windup_trans: "0.0, 0.0, 0.0"
    anti_windup_rot: "0.0, 0.0, 0.0"

    #BATTERY DISCHARGE
    bat_discharge_a: 0.0
    bat_discharge_b: 0.0